[rpc_endpoints]
local = "http://127.0.0.1:8545"

[profile.default]
solc = "0.8.20"
src = "src"
out = "out"
libs = ["lib"]
remappings = []
fs_permissions = [{ access = "read-write", path = "./"}]

[fuzz]
runs = 100